version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management  # Includes RabbitMQ with the management UI
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP protocol port for applications
      - "15672:15672" # Management UI port
    networks:
      - rabbitmq_network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_health" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  rabbitmq_network:
    driver: bridge
